# Generated by Django 4.1.1 on 2022-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('1', 'usd'), ('2', 'rub')], default='1', max_length=1),
        ),
    ]
