# Generated by Django 4.1.1 on 2022-09-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
